# Site settings
title: Blockchain Manchester
small_title: BM
email: andy@whatsthescore.co.uk
url: https://blockchainmanc.github.io/
description: "All things Blockchain, Love from Manchester"
keywords: "Blockchain"
strapline: "All things Blockchain, Love from Manchester"
meta_author: Manchester Blockcahin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 333333
  primary-rgb: "51,51,51"
  secondary: 666666
  secondary-dark: 444444

# Footer settings
footer:
  location: Location
  social: Social
  wallets: Wallets
  credits: Credits

# Social networks
social:
  - title: twitter
    url: http://twitter.com/blockchain_manc
  - title: github
    url: http://github.com/jekyll
  - title: slack
    url: https://blockchainmanc.slack.com

# wallets for tips
wallets:
  - coin: BTC
    account: 1FtAP6ktAr49wgF5m6xyQN5CPCdvQ8jnQK
  - coin: ETH
    account: 0x
  - coin: LTC
    account: 0x

# Build settings
markdown: kramdown
permalink: pretty
