# Site settings
title: Blockchain Manchester
small_title: BM
email: andy@whatsthescore.co.uk or james.morgan.e@googlemail.com
url: https://blockchainmanc.github.io/
description: "All things Blockchain, Love from Manchester"
keywords: "Blockchain"
strapline: "All things Blockchain, Love from Manchester"
meta_author: Manchester Blockcahin

# Google webmaster tools
google_verify:


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 666666
  primary-rgb: "102,102,102"
  secondary: 333333
  secondary-dark: 444444
  secondary-light: 999999

# Footer settings
footer:
  social: Social
  wallets: Wallets
  mailing: Mailing

# Social networks
social:
  - title: twitter
    url: http://twitter.com/blockchain_manc
  - title: github
    url: https://github.com/blockchainmanc
  - title: slack
    url: https://blockchainmanc.slack.com

# wallets for tips
wallets:
  - coin: BTC
    account: 1FtAP6ktAr49wgF5m6xyQN5CPCdvQ8jnQK
    img: /img/btc_qrcode_150x150.png
    explorer: https://blockexplorer.com/address/1FtAP6ktAr49wgF5m6xyQN5CPCdvQ8jnQK
  - coin: ETH
    account: 0x1652B165619b999065133428dd93023E7073254e
    img: /img/eth_qrcode_150x150.png
    explorer: https://etherscan.io/address/0x1652B165619b999065133428dd93023E7073254e
  - coin: LTC
    account: LddXUkD37wSkoLh23EptoRyFnpbzUZnLpk
    img: /img/ltc_qrcode_150x150.png
    explorer: https://live.blockcypher.com/ltc/address/LddXUkD37wSkoLh23EptoRyFnpbzUZnLpk/

# Build settings
markdown: kramdown
permalink: pretty
