# Site settings
title: Blockchain Manchester
small_title: BM
email: andy@whatsthescore.co.uk
url: https://blockchainmanc.github.io/
description: "All things Blockchain, Love from Manchester"
keywords: "Blockchain"
strapline: "All things Blockchain, Love from Manchester"
meta_author: Manchester Blockcahin

# Google webmaster tools
google_verify:


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 666666
  primary-rgb: "102,102,102"
  secondary: 333333
  secondary-dark: 444444
  secondary-light: 999999

# Footer settings
footer:
  social: Social
  wallets: Wallets

# Social networks
social:
  - title: twitter
    url: http://twitter.com/blockchain_manc
  - title: github
    url: http://github.com/jekyll
  - title: slack
    url: https://blockchainmanc.slack.com

# wallets for tips
wallets:
  - coin: BTC
    account: 1FtAP6ktAr49wgF5m6xyQN5CPCdvQ8jnQK
  - coin: ETH
    account: 0x
  - coin: LTC
    account: 0x

# Build settings
markdown: kramdown
permalink: pretty
